#!/bin/bash
pwd
#grep -v '^#|^$' < .projects.gws | { while IFS="|" read -r name repo; do
grep -v '^#' < .projects.gws | { while IFS="|" read -r name repo; do
#	echo "cd $name && $*" 
  if [ ! -z "$name" ]; then
	cd $name
	echo  "$name ;"
	git $*
	cd ..
  fi
done 
}
